version: '3.8'
services:

  mongodb:
    image: mongo:6-jammy
    container_name: web_site_storage
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  web-server:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./nginxdev.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/static

volumes:
  mongodb_data:
