version: '3.0'
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - web-server
    environment:
      - PYTHONPATH='~/app'
      - MONGO_HOST=172.20.0.3
      - MONGO_PORT=27017
      - SECRET_KEY=806a72e2e385b6bc576920bd966369a0965de5edf261a3e70add489314d49a8e
      - ACCESS_TOKEN_EXPIRE_MINUTES=180
      - REFRESH_TOKEN_EXPIRE_MINUTES=10080
      - ALGORITHM=HS256
    volumes:
      - ./app/static:/app/static
    networks:
      app_network:
        ipv4_address: 172.20.0.2

  mongodb:
    image: mongo:6-jammy
    container_name: web_site_storage
    volumes:
      - mongodb_data:/data/db
    networks:
      app_network:
        ipv4_address: 172.20.0.3

  web-server:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/static
      - ./dist:/usr/share/nginx/html
    networks:
      app_network:
        ipv4_address: 172.20.0.4


networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb_data: